# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: touch_force.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'touch_force.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11touch_force.proto\x12\rtouchforce.v1\"_\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x35\n\nget_uptime\x18\x03 \x01(\x0b\x32\x1f.touchforce.v1.GetUptimeRequestH\x00\x42\t\n\x07payload\"\x90\x01\n\x08Response\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12-\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1c.touchforce.v1.ErrorResponseH\x00\x12\x36\n\nget_uptime\x18\x03 \x01(\x0b\x32 .touchforce.v1.GetUptimeResponseH\x00\x42\t\n\x07payload\".\n\rErrorResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10GetUptimeRequest\"&\n\x11GetUptimeResponse\x12\x11\n\tuptime_ms\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'touch_force_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=36
  _globals['_REQUEST']._serialized_end=131
  _globals['_RESPONSE']._serialized_start=134
  _globals['_RESPONSE']._serialized_end=278
  _globals['_ERRORRESPONSE']._serialized_start=280
  _globals['_ERRORRESPONSE']._serialized_end=326
  _globals['_GETUPTIMEREQUEST']._serialized_start=328
  _globals['_GETUPTIMEREQUEST']._serialized_end=346
  _globals['_GETUPTIMERESPONSE']._serialized_start=348
  _globals['_GETUPTIMERESPONSE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
