/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_TOUCHFORCE_V1_TOUCH_FORCE_PB_H_INCLUDED
#define PB_TOUCHFORCE_V1_TOUCH_FORCE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _touchforce_v1_ErrorResponse {
    uint32_t code;
    char message[64];
} touchforce_v1_ErrorResponse;

typedef struct _touchforce_v1_GetUptimeRequest {
    char dummy_field;
} touchforce_v1_GetUptimeRequest;

/* Top-level wrapper for every host -> MCU message.

 Conventions (locked in by 2026-05-06 design spec):
   - request_id: opaque uint32 chosen by the host, echoed by the MCU
     in Response.request_id. SHOULD be non-zero (proto3 elides
     zero defaults on the wire, so 0 is indistinguishable from
     "unset").
   - Field 2 in both Request and Response is reserved across the
     whole protocol for Response.error, so command oneof slots
     start at field 3 with parallel numbers across Request/Response. */
typedef struct _touchforce_v1_Request {
    uint32_t request_id;
    pb_size_t which_payload;
    union _touchforce_v1_Request_payload {
        touchforce_v1_GetUptimeRequest get_uptime;
    } payload;
} touchforce_v1_Request;

typedef struct _touchforce_v1_GetUptimeResponse {
    /* Milliseconds since MCU boot (HAL_GetTick wraps at ~49.7 days,
 documented in protocol/README.md). */
    uint32_t uptime_ms;
} touchforce_v1_GetUptimeResponse;

/* Top-level wrapper for every MCU -> host message (in v1, only
 solicited responses; future versions may add an Event sibling). */
typedef struct _touchforce_v1_Response {
    uint32_t request_id;
    pb_size_t which_payload;
    union _touchforce_v1_Response_payload {
        touchforce_v1_ErrorResponse error;
        touchforce_v1_GetUptimeResponse get_uptime;
    } payload;
} touchforce_v1_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define touchforce_v1_Request_init_default       {0, 0, {touchforce_v1_GetUptimeRequest_init_default}}
#define touchforce_v1_Response_init_default      {0, 0, {touchforce_v1_ErrorResponse_init_default}}
#define touchforce_v1_ErrorResponse_init_default {0, ""}
#define touchforce_v1_GetUptimeRequest_init_default {0}
#define touchforce_v1_GetUptimeResponse_init_default {0}
#define touchforce_v1_Request_init_zero          {0, 0, {touchforce_v1_GetUptimeRequest_init_zero}}
#define touchforce_v1_Response_init_zero         {0, 0, {touchforce_v1_ErrorResponse_init_zero}}
#define touchforce_v1_ErrorResponse_init_zero    {0, ""}
#define touchforce_v1_GetUptimeRequest_init_zero {0}
#define touchforce_v1_GetUptimeResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define touchforce_v1_ErrorResponse_code_tag     1
#define touchforce_v1_ErrorResponse_message_tag  2
#define touchforce_v1_Request_request_id_tag     1
#define touchforce_v1_Request_get_uptime_tag     3
#define touchforce_v1_GetUptimeResponse_uptime_ms_tag 1
#define touchforce_v1_Response_request_id_tag    1
#define touchforce_v1_Response_error_tag         2
#define touchforce_v1_Response_get_uptime_tag    3

/* Struct field encoding specification for nanopb */
#define touchforce_v1_Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_uptime,payload.get_uptime),   3)
#define touchforce_v1_Request_CALLBACK NULL
#define touchforce_v1_Request_DEFAULT NULL
#define touchforce_v1_Request_payload_get_uptime_MSGTYPE touchforce_v1_GetUptimeRequest

#define touchforce_v1_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,error,payload.error),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_uptime,payload.get_uptime),   3)
#define touchforce_v1_Response_CALLBACK NULL
#define touchforce_v1_Response_DEFAULT NULL
#define touchforce_v1_Response_payload_error_MSGTYPE touchforce_v1_ErrorResponse
#define touchforce_v1_Response_payload_get_uptime_MSGTYPE touchforce_v1_GetUptimeResponse

#define touchforce_v1_ErrorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   code,              1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define touchforce_v1_ErrorResponse_CALLBACK NULL
#define touchforce_v1_ErrorResponse_DEFAULT NULL

#define touchforce_v1_GetUptimeRequest_FIELDLIST(X, a) \

#define touchforce_v1_GetUptimeRequest_CALLBACK NULL
#define touchforce_v1_GetUptimeRequest_DEFAULT NULL

#define touchforce_v1_GetUptimeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         1)
#define touchforce_v1_GetUptimeResponse_CALLBACK NULL
#define touchforce_v1_GetUptimeResponse_DEFAULT NULL

extern const pb_msgdesc_t touchforce_v1_Request_msg;
extern const pb_msgdesc_t touchforce_v1_Response_msg;
extern const pb_msgdesc_t touchforce_v1_ErrorResponse_msg;
extern const pb_msgdesc_t touchforce_v1_GetUptimeRequest_msg;
extern const pb_msgdesc_t touchforce_v1_GetUptimeResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define touchforce_v1_Request_fields &touchforce_v1_Request_msg
#define touchforce_v1_Response_fields &touchforce_v1_Response_msg
#define touchforce_v1_ErrorResponse_fields &touchforce_v1_ErrorResponse_msg
#define touchforce_v1_GetUptimeRequest_fields &touchforce_v1_GetUptimeRequest_msg
#define touchforce_v1_GetUptimeResponse_fields &touchforce_v1_GetUptimeResponse_msg

/* Maximum encoded size of messages (where known) */
#define TOUCHFORCE_V1_TOUCH_FORCE_PB_H_MAX_SIZE  touchforce_v1_Response_size
#define touchforce_v1_ErrorResponse_size         71
#define touchforce_v1_GetUptimeRequest_size      0
#define touchforce_v1_GetUptimeResponse_size     6
#define touchforce_v1_Request_size               8
#define touchforce_v1_Response_size              79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
